from Utility import columns_into_grid_string

lvl = [
    "XXXX#--XXXX",
    "XXXX---XXXX",
    "XXXX---XXXX",
    "XXXX--*XXXX",
    "XXXX#--XXXX",
    "XXXX---XXXX",
    "XXXX---XXXX",
    "XXXX---XXXX",
    "XXXX---XXXX",
    "XXXX--*XXXX",
    "XXXX#--XXXX",
    "XXXX---XXXX",
    "XXXX---XXXX",
    "XXXX--#XXXX",
    "XXXX-XXXXXX",
    "XXXX*XXXXXX",
    "XXXX-XXXXXX",
    "XXXX-XXXXXX",
    "XXXX---XXXX",
    "XXXX---XXXX",
    "XXXX-&-XXXX",
    "XXXX---XXXX",
    "XXXX---XXXX",
    "XXXX#--XXXX",
    "XXXX---XXXX",
    "XXXX---XXXX",
    "XXXX---XXXX",
    "XXXX-&-XXXX",
    "XXXX---XXXX",
    "XXXX---XXXX",
    "-----------",
    "-----------",
    "^---------^",
    "^---------^",
    "^-XXXXXXXX^",
    "^---------^"
]

print(columns_into_grid_string(lvl))